export { default as Main } from './Main/Main'
// export { default as BlogPage } from './Blog/BlogPage'
// export { default as ProjectPage } from './Project/ProjectPage'
export { default as CaseStudyPage } from './CaseStudyPage/CaseStudyPage'
export { default as About } from './About/About'
